name: medicine
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.13.9'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  get_storage: ^2.0.3
  awesome_notifications: 0.7.4+1
  http: ^0.13.5
  dio: ^5.0.0
  url_launcher: ^6.1.8
  flutter_native_splash: ^2.2.17
  intl: ^0.17.0
  lottie: ^2.2.0
  image_picker: ^0.8.6+2
  shared_preferences: ^2.0.18
  lazy_load_scrollview: ^1.3.0
  flutter_launcher_icons: ^0.13.1
  flutter_calendar_carousel: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  assets:
    - assets/img/

  fonts:
    - family: Manrope
      fonts:
        - asset: assets/font/manrope.ttf
    - family: Nunito
      fonts:
        - asset: assets/font/nunito.ttf

  uses-material-design: true

flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#3A3A3A"
  image: assets/img/logo-text.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/img/icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/img/icon.png"
    background_color: "#FFFFFF"
    theme_color: "#662C91"
  windows:
    generate: true
    image_path: "assets/img/icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/img/icon.png"
