name: medicine
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+7

environment:
  sdk: '>=2.19.0 <3.35.2'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  get_storage: ^2.0.3
  http: ^1.2.0
  dio: ^5.0.0
  url_launcher: ^6.1.8
  flutter_native_splash: ^2.4.1
  intl: ^0.20.2
  image_picker: ^1.0.7
  shared_preferences: ^2.0.18
  lazy_load_scrollview: ^1.3.0
  flutter_launcher_icons: ^0.14.4
  flutter_calendar_carousel: ^2.4.1
  device_info_plus: ^11.5.0
  mask_text_input_formatter: ^2.5.0
  permission_handler: ^12.0.1
  flutter_local_notifications: ^19.4.1
  timezone: ^0.10.1
  flutter_timezone: ^4.1.1
  aws_client: ^0.7.1
  flutter_animate: ^4.5.0
  firebase_core: ^4.1.0
  firebase_crashlytics: ^5.0.1
  firebase_analytics: ^12.0.1

dependency_overrides:
  win32: ^5.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  assets:
    - assets/img/
    - assets/audio/

  fonts:
    - family: Manrope
      fonts:
        - asset: assets/font/manrope.ttf
    - family: Nunito
      fonts:
        - asset: assets/font/nunito.ttf

  uses-material-design: true

flutter_native_splash:
  color: "#662C91"
  image: "assets/img/logo-white-transparent.png"
  android: true
  ios: true
  web: false

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/img/icon-white-transparent.png"
  adaptive_icon_background: "#662C91"
  adaptive_icon_foreground: "assets/img/icon-white-transparent.png"
  web:
    generate: true
    image_path: "assets/img/icon-white-transparent.png"
    background_color: "#662C91"
