// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaMJUcKVPvcTzrXgew-iE8EBXXgH3OrDQ',
    appId: '1:806699714327:web:62f1a426f1bbd63e205952',
    messagingSenderId: '806699714327',
    projectId: 'medicines-fa358',
    authDomain: 'medicines-fa358.firebaseapp.com',
    storageBucket: 'medicines-fa358.firebasestorage.app',
    measurementId: 'G-QL3V2RN78T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4sG793wev5huU_KWA-vrVthLIMAtrLi4',
    appId: '1:806699714327:android:0c5e67b3cd272304205952',
    messagingSenderId: '806699714327',
    projectId: 'medicines-fa358',
    storageBucket: 'medicines-fa358.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD19OzyXUNkKhv1ZXDk3FTXvb7GIpO9hJk',
    appId: '1:806699714327:ios:43a714b0ac0fef06205952',
    messagingSenderId: '806699714327',
    projectId: 'medicines-fa358',
    storageBucket: 'medicines-fa358.firebasestorage.app',
    iosBundleId: 'com.services.meds.medicine',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD19OzyXUNkKhv1ZXDk3FTXvb7GIpO9hJk',
    appId: '1:806699714327:ios:43a714b0ac0fef06205952',
    messagingSenderId: '806699714327',
    projectId: 'medicines-fa358',
    storageBucket: 'medicines-fa358.firebasestorage.app',
    iosBundleId: 'com.services.meds.medicine',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDaMJUcKVPvcTzrXgew-iE8EBXXgH3OrDQ',
    appId: '1:806699714327:web:af272fa821aca64d205952',
    messagingSenderId: '806699714327',
    projectId: 'medicines-fa358',
    authDomain: 'medicines-fa358.firebaseapp.com',
    storageBucket: 'medicines-fa358.firebasestorage.app',
    measurementId: 'G-N20SDV6YYY',
  );
}
